version: "3"

volumes:
  settings:
  database:

services:
  main:
    image: alpine
    restart: always
    command: tail -f /dev/null
    volumes:
    - settings:/etc
  database:
    image: postgres
    restart: always
    volumes:
    - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backup:
    image: borg-client
    restart: always
    volumes:
    - /root/borg-docker/client/id_rsa:/root/.ssh/id_rsa
    - /root/borg-docker/client/known_hosts:/root/.ssh/known_hosts
    - settings:/data/settings
    - database:/data/database
    environment:
      BORG_REPO: ssh://192.168.0.3:3000/srv/backup/example
      BORG_PASSPHRASE: "123"
      BORG_PREFIX: example
      BORG_SOURCE: /data
      BORG_FREQUENCY: "* * * * *"
