version: "3"

volumes:
  settings:
  database:

services:
  main:
    image: alpine
    restart: always
    command: tail -f /dev/null
    volumes:
    - settings:/etc
  database:
    image: postgres
    restart: always
    volumes:
    - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backup:
    image: borg-client
    restart: always
    volumes:
    - settings:/data/settings
    - database:/data/database
    environment:
      server: borg.example.com
      repository: /srv/example
      prefix: example
      frequency: 0 2 * * *
