version: "3"

volumes:
  settings:
  database:

services:
  main:
    image: alpine
    restart: always
    command: tail -f /dev/null
    volumes:
    - settings:/etc
  database:
    image: postgres
    restart: always
    volumes:
    - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backup:
    image: borg-client
    restart: always
    volumes:
    - ./ssh_host_ed25519_key.pub:/root/ssh_host_ed25519_key.pub
    - ./id_ed25519:/root/.ssh/id_ed25519
    - settings:/data/settings
    - database:/data/database
    environment:
      command: borg create --verbose --list --filter AME --stats
      repository: ssh://192.168.0.4:2222/srv/backup/example
      passphrase: "123"
      source: /data
      time: "* * * * *"
