version: "3"

services:
  backup:
    image: borg-server
    restart: always
    volumes:
    - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
    - ./clients:/root/clients
    - /mnt/backup:/srv/backup
    ports: ["2222:22"]
